# Generated by Django 3.0.3 on 2020-05-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='value',
            field=models.IntegerField(verbose_name='Valor'),
        ),
    ]
